const dropDownOptions = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"The Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo, Democratic Republic of the",
	"Congo, Republic of the",
	"Costa Rica",
	"Côte d’Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"East Timor (Timor-Leste)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"The Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea, North",
	"Korea, South",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia, Federated States of",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar (Burma)",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Sudan, South",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
]

const monthList = [
	"January",
	"February",
	"March",
	"April",
	"May",
	"June",
	"July",
	"August",
	"September",
	"October",
	"November",
	"December",
]

const timeList = [
	"00:00 AM",
	"00:15 AM",
	"00:30 AM",
	"00:45 AM",
	"01:00 AM",
	"01:15 AM",
	"01:30 AM",
	"01:45 AM",
	"02:00 AM",
	"02:15 AM",
	"02:30 AM",
	"02:45 AM",
	"03:00 AM",
	"03:15 AM",
	"03:30 AM",
	"03:45 AM",
	"04:00 AM",
	"04:15 AM",
	"04:30 AM",
	"04:45 AM",
	"05:00 AM",
	"05:15 AM",
	"05:30 AM",
	"05:45 AM",
	"06:00 AM",
	"06:15 AM",
	"06:30 AM",
	"06:45 AM",
	"07:00 AM",
	"07:15 AM",
	"07:30 AM",
	"07:45 AM",
	"08:00 AM",
	"08:15 AM",
	"08:30 AM",
	"08:45 AM",
	"08:00 AM",
	"08:15 AM",
	"08:30 AM",
	"08:45 AM",
	"09:00 AM",
	"09:15 AM",
	"09:30 AM",
	"09:45 AM",
	"10:00 AM",
	"10:15 AM",
	"10:30 AM",
	"10:45 AM",
	"11:00 AM",
	"11:15 AM",
	"11:30 AM",
	"11:45 AM",
	"12:00 PM",
	"12:15 PM",
	"12:30 PM",
	"12:45 PM",
	"01:00 PM",
	"01:15 PM",
	"01:30 PM",
	"01:45 PM",
	"02:00 PM",
	"02:15 PM",
	"02:30 PM",
	"02:45 PM",
	"03:00 PM",
	"03:15 PM",
	"03:30 PM",
	"03:45 PM",
	"04:00 PM",
	"04:15 PM",
	"04:30 PM",
	"04:45 PM",
	"05:00 PM",
	"05:15 PM",
	"05:30 PM",
	"05:45 PM",
	"06:00 PM",
	"06:15 PM",
	"06:30 PM",
	"06:45 PM",
	"07:00 PM",
	"07:15 PM",
	"07:30 PM",
	"07:45 PM",
	"08:00 PM",
	"08:15 PM",
	"08:30 PM",
	"08:45 PM",
	"08:00 PM",
	"08:15 PM",
	"08:30 PM",
	"08:45 PM",
	"09:00 PM",
	"09:15 PM",
	"09:30 PM",
	"09:45 PM",
	"10:00 PM",
	"10:15 PM",
	"10:30 PM",
	"10:45 PM",
	"11:00 PM",
	"11:15 PM",
	"11:30 PM",
	"11:45 PM",
]

const dropDownOptions2 = ["Matthew", "Mark", "Luke", "John", "Mary", "Pauline"]

// const elDDFlex = document.querySelectorAll(".ddfield__examples .ddfield__flex div:first-child")

DropdownField(
	".example-container>div>div",
	"Country",
	"Country",
	1,
	"dd1",
	dropDownOptions,
	{
		maxLines: 10,
		cssClassList: ["field3"],
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(2)>div>div",
	"Country",
	"Country",
	2,
	"dd2",
	dropDownOptions,
	{
		maxLines: 10,
		cssClassList: ["field3"],
		searchMode: "",
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(3)>div>div",
	"Country",
	"Country",
	3,
	"dd3",
	dropDownOptions,
	{
		maxLines: 10,
		cssClassList: ["field3"],
		ignoreFirstXCharacters: 2,
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(4)>div>div",
	"Country",
	"Country",
	4,
	"dd4",
	dropDownOptions,
	{
		maxLines: 10,
		cssClassList: ["field3"],
		autocomplete: true,
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(5)>div>div",
	"Country",
	"Country",
	5,
	"dd5",
	dropDownOptions,
	{
		cssClassList: ["field3"],
		maxLines: 5,
		showDropdownArrow: false,
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(6)>div>div",
	"Country",
	"Country",
	6,
	"dd6",
	dropDownOptions,
	{
		maxLines: 10,
		cssClassList: ["field3"],
		enterToggleDropdown: false,
		onClickToggleDropdown: false,
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(7)>div>div",
	"Country",
	"Country",
	7,
	"dd7",
	dropDownOptions,
	{
		maxLines: 10,
		cssClassList: ["field3"],
		onFocusOpenDropdown: false,
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(8)>div>div",
	"Month",
	"Month",
	8,
	"dd8",
	monthList,
	{
		maxLines: 10,
		cssClassList: ["field3"],
		onFocusOpenDropdown: false,
		typingOpenDropdown: false,
		arrowKeysNoDropdown: 2,
		autocomplete: true,
		enterToggleDropdown: false,
	}
)

DropdownField(
	".examples>.example-container:nth-of-type(9)>div>div",
	"Start Time",
	"Start Time",
	9,
	"dd9",
	timeList,
	{
		maxLines: 5,
		cssClassList: ["time-field"],
		onFocusOpenDropdown: false,
		typingOpenDropdown: false,
		arrowKeysNoDropdown: 2,
		autocomplete: true,
		enterToggleDropdown: false,
	}
)
